### ISSUE TITLE
Update Submodule Errors

### ISSUE THREAD

**Issue by ceceps** [gjerokrsteski/pimf-blog-mysql#5]
I am using windows to try some Phifm Blog Mysql and Twig version using your framework but I got error like this
when execute

``` sh
git submodule foreach git pull origin master
```

Here is the errors:

``` sh
Entering 'pimf-framework'                                                           
From https://github.com/gjerokrsteski/pimf-framework                                
 * branch            master     -> FETCH_HEAD                                       
Updating 4b75f83..d45b17f                                                           
error: Your local changes to the following files would be overwritten by merge:     
        core/Pimf/Util/Character.php                                                
Please, commit your changes or stash them before you can merge.                     
Aborting                                                                            
Stopping at 'pimf-framework'; script returned non-zero status.                      
```

Regards,

**Comment by gjerokrsteski** [comment]
Please update submodules using this commands:

              git submodule --quiet sync
              git submodule --quiet update --force --init --recursive
              git submodule foreach git pull --force origin master

With this commands you will enforce latest update of pimf-framework.

**Comment by ceceps** [comment]
I tried but no luck.  I try again with clone on this repo to other folder but still got error  like this 

```sh
D:\projects>git clone https://github.com/gjerokrsteski/pimf-blog-mysql myblog
Cloning into 'myblog'...
remote: Counting objects: 185, done.
remote: Total 185 (delta 0), reused 0 (delta 0), pack-reused 185
Receiving objects: 100% (185/185), 23.74 KiB | 0 bytes/s, done.
Resolving deltas: 100% (99/99), done.
Checking connectivity... done.

D:\projects>cd myblog

D:\projects\myblog>git submodule --quiet sync

D:\projects\myblog>git submodule --quiet update --force --init --recursive

D:\projects\myblog>git submodule foreach git pull --force origin master
Entering 'pimf-framework'
From https://github.com/gjerokrsteski/pimf-framework
 * branch            master     -> FETCH_HEAD
Updating 5bf7f7f..d45b17f
error: Your local changes to the following files would be overwritten by merge:
        core/Pimf/Util/Character.php
Please, commit your changes or stash them before you can merge.
Aborting
Stopping at 'pimf-framework'; script returned non-zero status.

D:\projects\myblog>
```

**Comment by gjerokrsteski** [comment]
If you have Git on windows - please try my last suggestion here.

When you clone this project repository, this parameter (set to true) ask git to change all line ending to CRLF. This behavior need to be changed before cloning the repository (or after for each files by hand). We recommand to turn this to off by running `git config --global core.autocrlf false` and `git config --global core.eol` lf before cloning. Then, after cloning, do not forget to turn the behavior back if you want to run other windows projects: `git config --global core.autocrlf true` and `git config --global core.eol crlf`.
